### ISSUE TITLE
Create Technical Design (technical description of the solution a description of all implemented functions and objects)

### ISSUE THREAD

**Issue by KurianJohn707** [KurianJohn707/Bi-Temporal-Historization-data-model#19]

**Comment by manish978973** [comment]
This is in progress......Will be deployed and closed at the earliest.

**Comment by manish978973** [comment]
First version of the Document has been designed and shared with the Team mates. Awaiting their response and feedbacks

**Comment by manish978973** [comment]
Final version of the doc has been presented to reviewerr for the feedback
