### ISSUE TITLE
Create Logical and Physical Data Model

### ISSUE THREAD

**Issue by abhijithremesh** [KurianJohn707/Bi-Temporal-Historization-data-model#2]

**Comment by vishnumohan1993** [comment]
[Logical Data Model.pdf](https://github.com/KurianJohn707/Bi-Temporal-Historization-data-model/files/2796659/Logical.Data.Model.pdf)
![physical data model-2018-11-23_17_56](https://user-images.githubusercontent.com/38094703/51754273-29e00b00-20bc-11e9-86e6-7609540e97cc.png)

done

**Comment by vishnumohan1993** [comment]
uploaded
