### ISSUE TITLE
Creation of Data Flow Diagram for the First presentation

### ISSUE THREAD

**Issue by manish978973** [KurianJohn707/Bi-Temporal-Historization-data-model#3]

**Comment by abhijithremesh** [comment]
![in memory dfd_NEW.jpeg](https://images.zenhubusercontent.com/5acf35a04b5806bc2bcec7e2/c00f4585-bb94-40ab-929f-691b5c00fdc4)[https://app.zenhub.com/files/158956202/db24383a-aca9-460f-95c1-2b8a74a59823/download](https://app.zenhub.com/files/158956202/db24383a-aca9-460f-95c1-2b8a74a59823/download)
