### ISSUE TITLE
Create Requirement Analysis Document

### ISSUE THREAD

**Issue by KurianJohn707** [KurianJohn707/Bi-Temporal-Historization-data-model#6]

**Comment by abhijithremesh** [comment]
[https://app.zenhub.com/files/158956202/f6308845-bb91-488b-bd2a-861f58fa0864/download](https://app.zenhub.com/files/158956202/f6308845-bb91-488b-bd2a-861f58fa0864/download)

**Comment by abhijithremesh** [comment]
[https://app.zenhub.com/files/158956202/560cf39a-9763-4105-ba6d-f45b35c2753f/download](https://app.zenhub.com/files/158956202/560cf39a-9763-4105-ba6d-f45b35c2753f/download)

Updated the document due to some formatting issues
