### ISSUE TITLE
Prepare MOMs 

### ISSUE THREAD

**Issue by abhijithremesh** [KurianJohn707/Bi-Temporal-Historization-data-model#8]

**Comment by manish978973** [comment]
mom 1 meeting 
[MOM_first_meeting.txt](https://github.com/KurianJohn707/Bi-Temporal-Historization-data-model/files/2799604/MOM_first_meeting.txt)

**Comment by manish978973** [comment]
[https://app.zenhub.com/files/158956202/9b1c628c-17f0-4b81-be29-2b38bfe8bf14/download](https://app.zenhub.com/files/158956202/9b1c628c-17f0-4b81-be29-2b38bfe8bf14/download)

**Comment by manish978973** [comment]
[https://app.zenhub.com/files/158956202/803ca2c0-dcde-4c1d-b56a-a1c387d82ee9/download](https://app.zenhub.com/files/158956202/803ca2c0-dcde-4c1d-b56a-a1c387d82ee9/download)

**Comment by manish978973** [comment]
MOM 2 and 3 has been updated

**Comment by manish978973** [comment]
Final MOM has been created ahead of the final presentation.

[PRESENTATION_DOC.txt](https://github.com/KurianJohn707/Bi-Temporal-Historization-data-model/files/3114475/PRESENTATION_DOC.txt)
